"""Update for new models

Revision ID: a3a1c0e315a8
Revises: 
Create Date: 2025-06-05 12:13:26.170950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a1c0e315a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.add_column('pull_requests', sa.Column('repo_id', sa.Integer(), nullable=False))
    op.add_column('pull_requests', sa.Column('branch', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('title', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('pull_requests', sa.Column('status', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('pull_requests', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    op.add_column('pull_requests', sa.Column('most_common_issue', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('ai_suggestions', sa.Text(), nullable=True))
    op.add_column('pull_requests', sa.Column('warnings_count', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('errors_count', sa.Integer(), nullable=True))
    op.add_column('pull_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pull_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_pull_requests_owner'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_pr_number'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repo'), table_name='pull_requests')
    op.create_foreign_key(None, 'pull_requests', 'repositories', ['repo_id'], ['id'])
    op.drop_column('pull_requests', 'repo')
    op.drop_column('pull_requests', 'pr_data')
    op.drop_column('pull_requests', 'pr_number')
    op.drop_column('pull_requests', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pull_requests', sa.Column('pr_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pull_requests', sa.Column('pr_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('pull_requests', sa.Column('repo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.create_index(op.f('ix_pull_requests_repo'), 'pull_requests', ['repo'], unique=False)
    op.create_index(op.f('ix_pull_requests_pr_number'), 'pull_requests', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_owner'), 'pull_requests', ['owner'], unique=False)
    op.drop_column('pull_requests', 'updated_at')
    op.drop_column('pull_requests', 'created_at')
    op.drop_column('pull_requests', 'errors_count')
    op.drop_column('pull_requests', 'warnings_count')
    op.drop_column('pull_requests', 'ai_suggestions')
    op.drop_column('pull_requests', 'most_common_issue')
    op.drop_column('pull_requests', 'last_reviewed')
    op.drop_column('pull_requests', 'score')
    op.drop_column('pull_requests', 'status')
    op.drop_column('pull_requests', 'description')
    op.drop_column('pull_requests', 'title')
    op.drop_column('pull_requests', 'branch')
    op.drop_column('pull_requests', 'repo_id')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
